name: gitwall
description: A modern Windows desktop wallpaper changer.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Framework
  fluent_ui: ^4.12.0
  bitsdojo_window: ^0.1.6
    
  # State Management
  provider: ^6.1.2

  # HTTP requests
  http: ^1.2.1

  # File system access
  path_provider: ^2.1.3
  path: ^1.9.0

  # User settings storage
  shared_preferences: ^2.2.3

  # Date formatting
  intl: ^0.20.2 


  # Windows API interaction
  win32: ^5.14.0
  win32_registry: ^2.1.0
  ffi: ^2.1.2
  tray_manager: ^0.5.1
  launch_at_startup: ^0.5.1
  window_manager: ^0.5.1
  
  # Screen information
  screen_retriever: ^0.2.0
  
  # Launching URLs
  url_launcher: ^6.2.6

  # File picking
  file_picker: ^8.1.2
  package_info_plus: ^8.3.1

  # Image caching
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - lib/assets/logo.ico
